---
swagger: "2.0"
info:
  description: "Web service for the NLP de-id method Philter developed by UCSF"
  version: "1.0.0"
  title: "Philter"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "thomas.schaffter@sagebionetworks.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "note"
  description: "Everything about your Notes"
  # externalDocs:
  #   description: "Find out more"
  #   url: "http://swagger.io"
schemes:
# - "https"
- "http"
paths:
  /deid:
    post:
      tags:
      - "note"
      summary: "De-identify the note specified"
      description: ""
      operationId: "deid"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Note object to de-identify"
        required: true
        schema:
          $ref: "#/definitions/Note"
      responses:
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.pet_controller"
definitions:
  Note:
    type: "object"
    properties:
      text:
        type: "string"
    example:
      text: "A text with sensitive information"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    example:
      code: 0
      type: "type"
      message: "message"
externalDocs:
  description: "View on GitHub"
  url: "https://github.com/data2health/philter-service"
